# Generated by Django 5.2 on 2025-04-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('goal_text', models.CharField(help_text='The goal that one has to meet to "win" the game', max_length=500)),
                ('title', models.CharField(help_text='The title of the game', max_length=150)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], help_text='Indicator of how hard is the game', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text that describes the goal of the problem.', max_length=200)),
                ('answer', models.CharField(help_text='The correct answer of the problem.', max_length=200)),
                ('score', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], help_text='How hard is the problem', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='THe text of the subject', max_length=500)),
                ('problems_to_solve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.problem')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the user', max_length=100)),
                ('email', models.EmailField(help_text='Email of the user', max_length=150)),
                ('password', models.CharField(help_text='The password for the user', max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('total_score', models.IntegerField()),
                ('level', models.IntegerField()),
                ('games_played', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.game')),
                ('problems_solved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.subject')),
            ],
        ),
    ]
